"""
run_pspire_pdb_region.py

Runs PSPire on topology-region PDB slices (Cytoplasmic, Transmembrane,
Extracellular/Lumenal) produced by run_picnic_pdb_region.py.

What it does per region:
  1. Copies region PDB files to a temp directory, prepending HEADER/TITLE/
     COMPND/SOURCE lines from the full-protein AF2 PDB so that mkdssp (v4+)
     recognises them as PDB format.
  2. Calls PSPire via subprocess on that temp directory.
  3. Collects scores from PSPire's CSV output.

Output: output/topology_scores_raw/PSPire_pdb_region_raw.csv
  Columns: UniProt_ID, region, n_residues, score

Run command (from project root):
  python3 run_pspire_pdb_region.py

Requires:
  - PSPire cloned to external_tools/PSPire/ (see README)
  - mkdssp (v4+) on PATH
  - conda env PSPire: /home/jake/miniconda3/envs/PSPire/
  - Region PDB files in data/alphafold_pdbs/regions/
    (generated by run_picnic_pdb_region.py)
"""

import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import pandas as pd

ROOT       = Path(__file__).parent
REGION_DIR = ROOT / "data/alphafold_pdbs/regions"
PDB_DIR    = ROOT / "data/alphafold_pdbs"
OUT_CSV    = ROOT / "output/topology_scores_raw/PSPire_pdb_region_raw.csv"
PSPIRE_PY  = ROOT / "external_tools/PSPire/PSPire.py"
PYTHON     = "/home/jake/miniconda3/envs/PSPire/bin/python3"

REGION_DIRS = {
    "Cytoplasmic":          REGION_DIR / "Cytoplasmic",
    "Transmembrane":        REGION_DIR / "Transmembrane",
    "Extracellular/Lumenal": REGION_DIR / "Extracellular_Lumenal",
}

MIN_RESIDUES = 10


def extract_uid(pdb_path: Path) -> str:
    m = re.search(r"AF-([A-Z0-9]+)-F\d+", pdb_path.name)
    if not m:
        raise ValueError(f"Cannot extract UniProt ID from {pdb_path.name}")
    return m.group(1)


def count_residues(pdb_path: Path) -> int:
    seen = set()
    with open(pdb_path) as fh:
        for line in fh:
            if line[:4] in ("ATOM", "HETA"):
                seen.add(int(line[22:26]))
    return len(seen)


def pdb_header_lines(full_pdb: Path) -> list[str]:
    """Return HEADER/TITLE/COMPND/SOURCE lines from the full AF2 PDB."""
    keep = []
    with open(full_pdb) as fh:
        for line in fh:
            if re.match(r"^(HEADER|TITLE|COMPND|SOURCE)", line):
                keep.append(line)
            elif line.startswith("ATOM"):
                break
    return keep


def build_pdb_with_header(full_pdb: Path, region_pdb: Path, dest: Path) -> None:
    """Write dest = HEADER lines from full_pdb + ATOM/TER/END from region_pdb."""
    lines = pdb_header_lines(full_pdb)
    with open(region_pdb) as fh:
        for line in fh:
            lines.append(line)
    dest.write_text("".join(lines))


def run_pspire_on_dir(pdb_dir: Path, project_name: str, work_dir: Path) -> pd.DataFrame | None:
    """
    Run PSPire on all PDB files in pdb_dir.
    Returns a DataFrame with columns [Uniprot_ID, Score, Include_IDRs] or None on failure.
    """
    out_csv = work_dir / f"{project_name}_scores.csv"
    cmd = [
        PYTHON, str(PSPIRE_PY),
        "-d", str(pdb_dir),
        "-o", str(out_csv),
        "-n", project_name,
    ]
    env = os.environ.copy()
    env["PATH"] = "/usr/bin:" + env.get("PATH", "")

    result = subprocess.run(
        cmd,
        cwd=str(work_dir),
        capture_output=True,
        text=True,
        env=env,
    )
    if result.returncode != 0:
        print(f"  PSPire failed (exit {result.returncode})", file=sys.stderr)
        if result.stderr.strip():
            print(result.stderr[-2000:], file=sys.stderr)
        return None

    if not out_csv.exists():
        print(f"  PSPire produced no output file: {out_csv}", file=sys.stderr)
        return None

    return pd.read_csv(out_csv)


def main():
    if not PSPIRE_PY.exists():
        sys.exit(f"PSPire not found at {PSPIRE_PY} — clone https://github.com/TongjiZhanglab/PSPire to external_tools/PSPire/")

    rows = []

    for region_label, region_pdb_dir in REGION_DIRS.items():
        if not region_pdb_dir.exists():
            print(f"Region dir not found, skipping: {region_pdb_dir}")
            continue

        pdb_files = sorted(region_pdb_dir.glob("AF-*-F1-model_v*.pdb"))
        print(f"\n{'='*60}")
        print(f"Region: {region_label}  ({len(pdb_files)} PDB files)")

        with tempfile.TemporaryDirectory(prefix="pspire_") as tmp:
            tmp = Path(tmp)
            pdb_input_dir = tmp / "input_pdbs"
            pdb_input_dir.mkdir()
            work_dir = tmp / "pspire_work"
            work_dir.mkdir()

            uid_to_nres = {}
            valid_pdbs = []

            for region_pdb in pdb_files:
                uid = extract_uid(region_pdb)
                n = count_residues(region_pdb)

                if n < MIN_RESIDUES:
                    print(f"  {uid}: skipping ({n} residues < {MIN_RESIDUES})")
                    continue

                full_pdb = next(PDB_DIR.glob(f"AF-{uid}-F1-model_v*.pdb"), None)
                if full_pdb is None:
                    print(f"  {uid}: no full PDB found, skipping")
                    continue

                dest = pdb_input_dir / region_pdb.name
                build_pdb_with_header(full_pdb, region_pdb, dest)
                uid_to_nres[uid] = n
                valid_pdbs.append(uid)

            print(f"  Running PSPire on {len(valid_pdbs)} proteins...")
            project_name = f"pspire_{region_label.replace('/', '_').replace(' ', '_')}"
            scores_df = run_pspire_on_dir(pdb_input_dir, project_name, work_dir)

            if scores_df is None:
                print(f"  !! PSPire returned no results for region {region_label}")
                continue

            # PSPire outputs: Uniprot_ID, Score, Include_IDRs, ...
            for _, row in scores_df.iterrows():
                uid = str(row["Uniprot_ID"])
                score = float(row["Score"])
                n = uid_to_nres.get(uid, 0)
                rows.append({"UniProt_ID": uid, "region": region_label, "n_residues": n, "score": score})
                print(f"  {uid}  n={n:4d}  score={score:.4f}")

    if not rows:
        sys.exit("No scores collected — check errors above")

    df = pd.DataFrame(rows)
    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(OUT_CSV, index=False)
    print(f"\nWrote {len(df)} rows to {OUT_CSV}")
    print(df.groupby("region")["score"].describe().round(3).to_string())


if __name__ == "__main__":
    main()
