"""
run_pspire_pdb_concatenated.py

Runs PSPire on the structural 'pdb_concatenated' PDBs (built by
build_concatenated_pdbs.py): same true 3D coordinates as the pdb_region
PDBs, but residues renumbered into one continuous chain (1..N) with no
numbering gaps at fragment boundaries, mirroring what sequence-level
'concatenated' does for sequence tools. Parallel to run_pspire_pdb_region.py.

Output: output/topology_scores_raw/PSPire_pdb_concatenated_raw.csv
  Columns: UniProt_ID, region, n_residues, n_fragments, score

Run command (from project root):
  python3 run_pspire_pdb_concatenated.py

Requires:
  - PSPire cloned to external_tools/PSPire/
  - mkdssp (v4+) on PATH
  - conda env pspire_env
  - concatenated PDB files in data/alphafold_pdbs/concatenated/
    (generated by build_concatenated_pdbs.py)
"""

import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

import pandas as pd

ROOT       = Path(__file__).parent
MANIFEST   = ROOT / "data/alphafold_pdbs/concatenated_manifest.csv"
PDB_DIR    = ROOT / "data/alphafold_pdbs"
OUT_CSV    = ROOT / "output/topology_scores_raw/PSPire_pdb_concatenated_raw.csv"
PSPIRE_PY  = ROOT / "external_tools/PSPire/PSPire.py"
PYTHON     = "/home/jake/.claude-science/conda/envs/pspire_env/bin/python3.10"

MIN_RESIDUES = 10


def pdb_header_lines(full_pdb: Path) -> list[str]:
    """Return HEADER/TITLE/COMPND/SOURCE lines from the full AF2 PDB."""
    keep = []
    with open(full_pdb) as fh:
        for line in fh:
            if re.match(r"^(HEADER|TITLE|COMPND|SOURCE)", line):
                keep.append(line)
            elif line.startswith("ATOM"):
                break
    return keep


def build_pdb_with_header(full_pdb: Path, cat_pdb: Path, dest: Path) -> None:
    """Write dest = HEADER lines from full_pdb + ATOM/TER/END from cat_pdb."""
    lines = pdb_header_lines(full_pdb)
    with open(cat_pdb) as fh:
        for line in fh:
            lines.append(line)
    dest.write_text("".join(lines))


def run_pspire_on_dir(pdb_dir: Path, project_name: str, work_dir: Path) -> pd.DataFrame | None:
    out_csv = work_dir / f"{project_name}_scores.csv"
    cmd = [
        PYTHON, str(PSPIRE_PY),
        "-d", str(pdb_dir),
        "-o", str(out_csv),
        "-n", project_name,
    ]
    env = os.environ.copy()
    env["PATH"] = "/usr/bin:" + env.get("PATH", "")

    result = subprocess.run(cmd, cwd=str(work_dir), capture_output=True, text=True, env=env)
    if result.returncode != 0:
        print(f"  PSPire failed (exit {result.returncode})", file=sys.stderr)
        if result.stderr.strip():
            print(result.stderr[-2000:], file=sys.stderr)
        return None
    if not out_csv.exists():
        print(f"  PSPire produced no output file: {out_csv}", file=sys.stderr)
        return None
    return pd.read_csv(out_csv)


def main():
    if not PSPIRE_PY.exists():
        sys.exit(f"PSPire not found at {PSPIRE_PY}")

    manifest = pd.read_csv(MANIFEST)
    rows = []

    for region_label, sub in manifest.groupby("region"):
        print(f"\n{'='*60}")
        print(f"Region: {region_label}  ({len(sub)} PDB files)")

        with tempfile.TemporaryDirectory(prefix="pspire_cat_") as tmp:
            tmp = Path(tmp)
            pdb_input_dir = tmp / "input_pdbs"
            pdb_input_dir.mkdir()
            work_dir = tmp / "pspire_work"
            work_dir.mkdir()

            uid_to_meta = {}
            for _, r in sub.iterrows():
                uid = r["UniProt_ID"]
                n = r["n_residues"]
                if n < MIN_RESIDUES:
                    print(f"  {uid}: skipping ({n} residues < {MIN_RESIDUES})")
                    continue

                cat_pdb = ROOT / r["pdb_path"]
                full_pdb = next(PDB_DIR.glob(f"AF-{uid}-F1-model_v*.pdb"), None)
                if full_pdb is None:
                    print(f"  {uid}: no full PDB found, skipping")
                    continue

                dest = pdb_input_dir / cat_pdb.name
                build_pdb_with_header(full_pdb, cat_pdb, dest)
                uid_to_meta[uid] = (n, r["n_fragments"])

            print(f"  Running PSPire on {len(uid_to_meta)} proteins...")
            project_name = f"pspire_cat_{region_label.replace('/', '_').replace(' ', '_')}"
            scores_df = run_pspire_on_dir(pdb_input_dir, project_name, work_dir)

            if scores_df is None:
                print(f"  !! PSPire returned no results for region {region_label}")
                continue

            for _, row in scores_df.iterrows():
                uid = str(row["Uniprot_ID"])
                score = float(row["Score"])
                n, n_frag = uid_to_meta.get(uid, (0, None))
                rows.append({
                    "UniProt_ID": uid, "region": region_label,
                    "n_residues": n, "n_fragments": n_frag, "score": score,
                })
                print(f"  {uid}  n={n:4d}  frag={n_frag}  score={score:.4f}")

    if not rows:
        sys.exit("No scores collected — check errors above")

    df = pd.DataFrame(rows)
    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(OUT_CSV, index=False)
    print(f"\nWrote {len(df)} rows to {OUT_CSV}")
    print(df.groupby("region")["score"].describe().round(3).to_string())


if __name__ == "__main__":
    main()
